### ISSUE TITLE
考虑支持 mirai-hibernate-plugin 吗？

### ISSUE THREAD

**Issue by Initial-heart-1** [gsycl2004/XXYan#4]
详见 [这里](https://github.com/cssxsh/mirai-hibernate-plugin)
主要是之前就在用这个插件，已经有挺多记录了，不用起来怪可惜的（
![image](https://user-images.githubusercontent.com/63091661/179158308-8f6b22b9-3d56-49f5-8051-10672276e36f.png)
而且能 MySQL，高压场景表现会好些
需求估计少，要不行直接 close 吧

**Comment by cssxsh** [comment]
......
